version: '3.8'
services:
  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file:
      - mysql.env
    ports:
      - "3310:3306"
    networks:
      - dark-scorpion
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  dark-scorpion:

volumes:
  mysql-data: